// 
// File generated by `npm run generate:blank place/components/trip`
//
// After activate you can access from 
//
// http://localhost:5000/#/dev/place/components/trip
//
//
// for ACTIVATE please add IMPORT and ROUTE in `src/app/dashboard/dashboard.ts`
//
// /*
//  * Here is router imports
//  */
// import { Trip } from './place/components/trip';
// 
//  ..
//  ..
//  ..
//
//  @RouteConfig([
//      { path: '/dev/place/components/trip', component: Trip, name: 'Tripplace-components/trip' },   
//
//  ..
//  .. 
//


import { Component, ViewContainerRef, ElementRef } from '@angular/core';

import { AppState } from '../app.service';


import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Comment } from '../model/comment';
import { Observable } from 'rxjs/Rx';


import { Router, ActivatedRoute, Params } from '@angular/router';

import * as numeral from 'numeral';
import * as moment from 'moment';
import * as _ from 'lodash';

import { AlertComponent } from 'ng2-bootstrap/ng2-bootstrap';

import {EviService} from '../../shared/services/evi.service';

let $ = require('jquery/dist/jquery.js');
let foundation = require('foundation-sites/dist/js/foundation.js');

@Component({
  // The selector is what angular internally uses
  // for `document.querySelectorAll(selector)` in our index.html
  // where, in this case, selector is the string 'home'
  selector: 'home',  // <home></home>
  // We need to tell Angular's Dependency Injection which providers are in our app.
  providers: [
  ],
   styleUrls: [ './trip.component.scss' ],
  // Every Angular template is first compiled by the browser before Angular runs it's compiler
  templateUrl: './trip.component.html'
})
export class TripComponent {
  // Set our default values
    localState = { value: '' };

  data : ['1', '20', '300'];
    reshello = '';
  // TypeScript public modifiers
  constructor(private evi : EviService, private route : ActivatedRoute, private _el: ElementRef ) {
      
  }

  ngOnInit() {

    let loda = _.chunk(['a', 'b', 'c', 'd'], 2);

    let numer = numeral(100);
      console.log('hello `Home` component', numer.format('0.2'), loda);

      var mom = moment().format('MMMM Do YYYY, h:mm:ss a'); 

      //console.log('ahoj', APISERVER, mom);
    // this.title.getData().subscribe(data => this.data = data);
  }

  ngAfterViewInit() {
    $(this._el.nativeElement.ownerDocument).foundation();
    //console.log('$(this._el.nativeElement.ownerDocument).foundation()');
  }

}