// 
// File generated by `npm run generate:blank trip/components/list/list`
//
// After activate you can access from 
//
// http://localhost:5000/#/dev/trip/components/list/list
//
//
// for ACTIVATE please add IMPORT and ROUTE in `src/app/dashboard/dashboard.ts`
//
// /*
//  * Here is router imports
//  */
// import { List } from './trip/components/list/list';
//

import { Component, ViewContainerRef, ElementRef, Input, Output } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { Router, ActivatedRoute, Params } from '@angular/router';

import * as numeral from 'numeral';
import * as moment from 'moment';
import * as _ from 'lodash';

import { AlertComponent } from 'ng2-bootstrap/ng2-bootstrap';
import {EviService} from '../../../shared/services/evi.service';

import {TripService} from '../../services/trip.services'

let $ = require('jquery/dist/jquery.js');
let foundation = require('foundation-sites/dist/js/foundation.js');

@Component({
  // The selector is what angular internally uses
  // for `document.querySelectorAll(selector)` in our index.html
  // where, in this case, selector is the string 'home'
  selector: 'home',  // <home></home>
  // We need to tell Angular's Dependency Injection which providers are in our app.
  providers: [
  ],
   styleUrls: [ './list.component.scss' ],
  // Every Angular template is first compiled by the browser before Angular runs it's compiler
  templateUrl: './list.component.html'
})
export class TripListComponent {

  public trips = [];
 
  // TypeScript public modifiers
  constructor(private evi : EviService, private route : ActivatedRoute, private _el: ElementRef,
                private _tripService: TripService ) {
      
  }

  public ngOnInit() {
    this._tripService.loadAllTrips((data)=>{
      this.trips = data;
    });
  }

  public ngAfterViewInit() {
    $(this._el.nativeElement.ownerDocument).foundation();
  }

}