// 
// File generated by `npm run generate:blank trip/components.view/place-info/place-info`
//
// After activate you can access from 
//
// http://localhost:5000/#/dev/trip/components.view/place-info/place-info
//
//
// for ACTIVATE please add IMPORT and ROUTE in `src/app/dashboard/dashboard.ts`
//
// /*
//  * Here is router imports
//  */
// import { Place-info } from './trip/components.view/place-info/place-info';
//

import { Component, ViewContainerRef, ElementRef, Input, Output,EventEmitter } from '@angular/core';
import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Observable } from 'rxjs/Rx';
import { Router, ActivatedRoute, Params } from '@angular/router';
import { ResizeEvent } from 'angular-resizable-element';

import * as numeral from 'numeral';
import * as moment from 'moment';
import * as _ from 'lodash';

import { AlertComponent } from 'ng2-bootstrap/ng2-bootstrap';
import {EviService} from '../../../shared/services/evi.service';

import {TripService} from '../../services/trip.services';

let $ = require('jquery/dist/jquery.js');
let foundation = require('foundation-sites/dist/js/foundation.js');

import {CloudinaryImageComponent} from 'ng2-cloudinary';

const imageFrameCompensateForBottomDepartingTitle = 48;

@Component({
  // The selector is what angular internally uses
  // for `document.querySelectorAll(selector)` in our index.html
  // where, in this case, selector is the string 'home'
  selector: 'g4t-place-info-view',  // <home></home>
  // We need to tell Angular's Dependency Injection which providers are in our app.
  providers: [
  ],
   styleUrls: [ './place-info.component.scss' ],
  // Every Angular template is first compiled by the browser before Angular runs it's compiler
  templateUrl: './place-info.component.html'
})
export class PlaceInfoViewComponent {
  @Output('onDelete') onDeleteEmitter = new EventEmitter();
  @Output('onResize') onResizeEmitter = new EventEmitter();

  @Input('place') place : any;
  @Input('places') places: Array<any>;
  @Input('index') index : number;
  @Input('wayUuid') uuid: string;
  
  timerToSave = null;
  timerToShow = null;

  //public fromPlace : any;
  public toPlace : any;

  public info : any;

  public imageFrameHeight = 0;

  public dateDeparting : number;
  

  public style: any = {
    height: '100px',
    //lineHeight: '300px'
  };

  public visitingStyle : any = {
    marginTop:'-100px'
  }

  public hours: number;
  public minutes: number;
  
  // TypeScript public modifiers
  constructor(private evi : EviService, private route : ActivatedRoute, private _el: ElementRef, private _tripService : TripService) {
      
  }

  public ngOnInit() {
  
  }

  public ngAfterViewInit() {
    //$(this._el.nativeElement.ownerDocument).foundation();
    
  }
  
  public ngOnChanges(changes: any){
    

    let height = Math.round(this.place.stayover/2)
    let heightFromMinutes = height + 'px';

    this.style.height = heightFromMinutes;
    //this.style.lineHeight = heightFromMinutes;

    let toIndex = this.index+1;
    if(toIndex == this.places.length){
      // this is last one
      toIndex = 0;
    }
    
    //this.fromPlace = this.place;
    this.toPlace = this.places[toIndex];

    this.info = this.place.infoplace

    

    
   
    this.recountTime(this.place.stayover);

    this.imageFrameHeight = height - imageFrameCompensateForBottomDepartingTitle;

    this.updateVisitorBar(height);
    //console.log(this.index, this.place, this.places);
  }

  public recountTime(timestay){
    this.hours = Math.floor( timestay /60);          
    this.minutes = timestay % 60;
  }
  
  validate(event: ResizeEvent): boolean {
    const MIN_DIMENSIONS_PX: number = 10;
    if (event.rectangle.width < MIN_DIMENSIONS_PX || event.rectangle.height < MIN_DIMENSIONS_PX) {
      return false;
    }
    return true;
  }

  onResizing(event: ResizeEvent): void {
    this.style = {
      //lineHeight: `${event.rectangle.height}px`,
      height: `${event.rectangle.height}px`
    };

    

    if(this.timerToShow){
      return;
    }

    let totalMinutes = Math.round(event.rectangle.height*2);

    this.imageFrameHeight = event.rectangle.height - imageFrameCompensateForBottomDepartingTitle;
    this.updateVisitorBar(event.rectangle.height);

    if(this.timerToSave){
      clearTimeout(this.timerToSave);
    }

    

    this.timerToSave = window.setTimeout(()=>{
      this._tripService.placeStayover(this.uuid, this.place.id, totalMinutes, ()=>{});
    }, 250);

    this.timerToShow = window.setTimeout(()=>{
      this.recountTime(totalMinutes);
      this.timerToShow = null;
      // recount all times arrives and depart
      this.place.stayover = event.rectangle.height*2;

      console.log(this.place.stayover);
      this.onResizeEmitter.emit();
      
    },1);

    
    
    
  }

  updateVisitorBar(height){
    this.visitingStyle.marginTop = '-' + (height -7) + 'px';
  }

  onDelete(){
    this.onDeleteEmitter.emit(this.place.id);
     
  }

}