// 
// File generated by `npm run generate:blank shared/components/Loader/Loader`
//
// After activate you can access from 
//
// http://localhost:5000/#/dev/shared/components/Loader/Loader
//
//
// for ACTIVATE please add IMPORT and ROUTE in `src/app/dashboard/dashboard.ts`
//
// /*
//  * Here is router imports
//  */
// import { Loader } from './shared/components/Loader/Loader';
// 
//  ..
//  ..
//  ..
//
//  @RouteConfig([
//      { path: '/dev/shared/components/Loader/Loader', component: Loader, name: 'Loadershared-components/Loader/Loader' },   
//
//  ..
//  .. 
//


import { Component, ViewContainerRef, Input, Output } from '@angular/core';

import { AppState } from '../app.service';


import { Http, Response, Headers, RequestOptions } from '@angular/http';
import { Comment } from '../model/comment';
import { Observable } from 'rxjs/Rx';


import { Router, ActivatedRoute, Params } from '@angular/router';

import * as numeral from 'numeral';
import * as moment from 'moment';
import * as _ from 'lodash';

import { AlertComponent } from 'ng2-bootstrap/ng2-bootstrap';

import {EviService} from '../../../shared/services/evi.service';

export class LoaderM<Model> {
  data : Model = null;
  loading : boolean = true;
  error: any = null;
}


@Component({
  // The selector is what angular internally uses
  // for `document.querySelectorAll(selector)` in our index.html
  // where, in this case, selector is the string 'home'
  selector: 'ops-loader-component',  // <home></home>
  // We need to tell Angular's Dependency Injection which providers are in our app.
  providers: [
  ],
   styleUrls: [ './loader.component.scss' ],
  // Every Angular template is first compiled by the browser before Angular runs it's compiler
  templateUrl: './loader.component.html'
})
export class LoaderComponent {
  @Input() data : LoaderM<any> = new LoaderM<any>();
  @Input() nocontent : boolean = true;
  constructor(private ops : EviService, private route : ActivatedRoute ) {
      
  }

  ngOnInit() {

  }


}